import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Layout from "../../components/layout";
import { fetchGet } from "../../utils/fetch";

export async function getServerSideProps(context) {
  const tanks = await fetchGet(`${process.env.APP_URL}/api/tank/all`);

  var uniqueTankTypes = [
    ...new Set(Object.keys(tanks).map((e) => tanks[e].Type)),
  ];

  let totalGallons = 0;
  tanks.map((t) => {
    totalGallons += Number(t.Size);
  });
  return {
    props: {
      numTanks: tanks.length,
      totalGallons: totalGallons,
      uniqueTankTypes: uniqueTankTypes.length,
    },
  };
}
export default function Home({ numTanks, totalGallons, uniqueTankTypes }) {
  return (
    <div class="h-full">
      <Head>
        <title>AquariumML</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h3 class="text-2xl font-bold">Tanks </h3>
        <div class="stats stats-vertical lg:stats-horizontal shadow text-teal-400">
          <div class="stat hover:bg-slate-300 hover:cursor-pointer">
            <div class="stat-title"># Tanks</div>
            <div class="stat-value">{numTanks}</div>
          </div>

          <div class="stat">
            <div class="stat-title">Types of tanks</div>
            <div class="stat-value">{uniqueTankTypes}</div>
          </div>

          <div class="stat">
            <div class="stat-title"># Gallons</div>
            <div class="stat-value">{totalGallons}</div>
          </div>

          <div class="stat">
            <div class="stat-title">Oldest tank</div>
            <div class="stat-value">6 years</div>
          </div>

          <div class="stat">
            <div class="stat-title"># Gallons water changed</div>
            <div class="stat-value">1,200</div>
          </div>
        </div>
        <br />
        <div class="divider"></div>
        <h3 class="text-2xl font-bold">Fish</h3>
        <div class="stats stats-vertical lg:stats-horizontal shadow text-cyan-400">
          <Link href="/tank">
            <a>
              <div class="stat hover:bg-slate-300 hover:cursor-pointer">
                <div class="stat-title"># Fish</div>
                <div class="stat-value">49</div>
              </div>
            </a>
          </Link>

          <div class="stat">
            <div class="stat-title"># Gallons</div>
            <div class="stat-value">{totalGallons}</div>
          </div>

          <div class="stat">
            <div class="stat-title"># Gallons water changed</div>
            <div class="stat-value">1,200</div>
          </div>
        </div>
      </Layout>
    </div>
  );
}
