import Head from "next/head";
import Image from "next/image";
import Layout from "../components/layout";
import { fetchGet } from "../utils/fetch";

export async function getServerSideProps(context) {
  const tanks = await fetchGet(`${process.env.APP_URL}/api/tank/all`);

  let totalGallons = 0;
  tanks.map((t) => {
    totalGallons += Number(t.Size);
  });
  return {
    props: {
      numTanks: tanks.length,
      totalGallons: totalGallons,
    },
  };
}
export default function Home({ numTanks, totalGallons }) {
  return (
    <div class="h-full">
      <Head>
        <title>AquariumML</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        =total # tanks {numTanks} =total gallons: {totalGallons}= =water changes
        performed= <br />
        ===recent activity=====
      </Layout>
      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
